name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du code
      - uses: actions/checkout@v3

      # 2️⃣ Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Installer SonarScanner
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin
          echo "$PATH"

      # 4️⃣ Vérifier que SonarScanner fonctionne
      - name: Check SonarScanner
        run: sonar-scanner --version

      # 5️⃣ Lancer l’analyse
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ squ_99328c2b18c229c94cc1dc80efd571e1ac87f305}}
        run: |
          ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
          -Dsonar.projectKey=ecommerce \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=squ_99328c2b18c229c94cc1dc80efd571e1ac87f305

